export enum ActionType {
  // SideMenu Action
  OPEN = "app/openSideMenu",
  CLOSE = "app/closeSideMenu",
  SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST',
  SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS',
  SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE',
  MOVIE_BOOKMARK_ON = 'MOVIE_BOOKMARK_ON',
  MOVIE_BOOKMARK_OFF = 'MOVIE_BOOKMARK_OFF'
}
